### ISSUE TITLE
Component colours verbeteren

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library-infra#106]
```[tasklist]
### Tasks
- [ ] Ontwerpen in figma
- [ ] Documentatie schrijven
- [ ] Overdragen aan Woweb + Joost
- [ ] Woweb developen in comp biblio
```
