### ISSUE TITLE
Component grids verbeteren?

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/component-library-infra#107]
Nog overleggen of en hoe we dit willen.

```[tasklist]
### Tasks
- [ ] Ontwerpen in figma
- [ ] Documentatie schrijven
- [ ] Overdragen aan Woweb + Joost
- [ ] Woweb developen in comp biblio
```
